teritorio/vido

components/Home/Home.vue

just to be sure this is the behaviour you wanted i removed the point-events-none,
what was it for ?

:bug: #856 add point-scroll-event in header

---

components/Home/Home.vue
components/Home/Menu.vue

Done for the bottom menu, necessay in desktop ?

:bug: #50 scroll top on menu navigation in bottom menu

---

components/Home/Home.vue

Fix-103 : flex on many category selected

---

components/Home/Embedded.vue

To check if this is well what I understood
https://github.com/teritorio/vido/issues/112

fix-112: update layout to have category selector updated on map size

---

components/PoisCard/PoiCardContent.vue
lib/colorDefiner.ts

feat: poiCard detail button has poi color

---

README.md
components/Layout/Header.vue
components/Layout/PoiLayout.vue
components/PoisCard/PoisDeck.vue
components/PoisDetails/Carousel.vue
components/PoisDetails/FieldsGroup.vue
components/PoisDetails/PoiDetails.vue
components/PoisList/CategorySelector.vue
pages/poi/[id]/details.vue
plugins/vido-config.ts
stores/menu.ts
tailwind.config.js

First draft do not hesitate to tell me the modification needed

feat: init css on print #18

---

components/Fields/Stars.vue
stores/map.ts

Had to force Number casting in component's template

Always one star on favorite notebook

---

components/PoisCard/PoiCardContent.vue

Use fill color as button background color.

Fix PoiCard detail button color

---

components/Fields/AddressField.vue
components/Fields/Field.vue
components/Fields/RoutesField.vue
composables/useField.ts

I will open a new PR for RouteField vue-i18n interpolations, once this one is merged.
For the rest of comments it just informationnal about State of the Art and later modification to be done.

Create use field composable + refactor RoutesField / AddressField

---

components/PoisList/PoisTable.vue

I fixed a responsiveness issue on input filter which is not centered on mobile

Details link is inconsistent between popup and list mode

---

components/Fields/Stars.story.vue
components/Fields/Stars.vue

Remove type error on Stars story:

Fix Stars story

---

components/Fields/OpeningHours.test.js
package.json
yarn.lock

Later I will apply the same rules as Clearance Frontend and same workflow (commitlint, styles linting handled by Eslint, git Hook etc ...)
Later because it will change almost all the files of the project ...

Upgrade eslint

---

components/PoisList/PoisTable.vue

It appears to be a Vuetify internal issue. For the moment as a fix we can load the component client-side only.
@frodrigo do you see any problem with this solution ?

PoisTable hydration mismatch

---

cypress.config.ts
cypress/e2e/poi/detail-simple.cy.ts
package.json

Since we added category name in page title, the limit of 70 character (htmlValidate default) is reached

Deactivate long-text rule

---

components/Home/Home.vue
components/MainMap/MapFeatures.vue
package.json
stores/map.ts
yarn.lock

Waiting for https://github.com/teritorio/maplibre-gl-teritorio-cluster/pull/28 to be merge and new version to be published.

No pin marker on poi selected from search

---

components/MainMap/MapFeatures.vue

@frodrigo Do you think we can have bus line data from Elasa dev in order to test it ?

Add feature color_fill into accepted cluster colors

---

components/Home/Embedded.vue
components/Home/Home.vue
components/MainMap/MapFeatures.story.vue
components/MainMap/MapFeatures.vue
components/Map/MapBase.vue
components/Map/MapPois.vue
lib/bbox.ts

Apply script setup style on:
- MapPois
- MapFeatures
- MapBase
Fix bug related to POI layer init (missing POIs on inital load)

Apply script setup style to Map components

---

components/MainMap/MapFeatures.vue
components/PoisDetails/Route/RouteMap.vue
cypress.config.ts
stores/menu.ts

Fix https://github.com/teritorio/vido/issues/507 as well

Display line as deps

---

cypress.config.ts
plugins/tracking.ts

Second commit is cherry-picked from develop, it fixes CI issue with Cypress config file.

GTM bypass cookies

---

components/PoisCard/PoiCardLight.vue

Source: https://tourism-seignanx.beta.appcarto.teritorio.xyz/poi/8498/details#map=13.36/43.55723/-1.48715

Image overlapping

---

locales/en-GB.ts
locales/es-ES.ts
locales/fr-FR.ts

@frodrigo Review just for spanish trad :)

Update placeholderAdd translation

---

components/Fields/Field.vue
components/Home/SelectedCategories.vue
components/Isochrone/IsochroneStatus.vue
components/Layout/PoiLayout.vue
components/MainMap/MapFeatures.vue
components/Menu/Category.vue
components/Menu/Group.vue
components/Menu/Item.vue
components/Menu/Link.vue
components/PoisCard/PoiCard.vue
components/PoisCard/PoiCardContent.vue
components/PoisCard/PoiCardLight.vue
components/PoisCard/PoisDeck.stories.ts
components/PoisCard/PoisDeck.story.vue
components/PoisDetails/Block.vue
components/PoisDetails/FieldsGroup.story.vue
components/PoisDetails/FieldsGroup.vue
components/PoisDetails/PoiDetails.vue
components/PoisDetails/Route/RouteMap.vue
components/PoisList/PoisTable.vue
components/UI/TeritorioIcon.vue
components/UI/TeritorioIconBadge.vue
composables/useFeature.ts
lib/apiMenu.ts
lib/apiPoiDeps.ts
lib/apiPois.ts
lib/clusters.ts
lib/mapPois.ts
lib/vectorTilesPois.ts
pages/index.vue

- Invert colorFill / colorText on waypoints

Bus support contrasted color

---

components/Home/Home.vue
components/Home/MenuBlockBottom.vue
components/Layout/Header.vue
components/MainMap/FavoriteMenu.vue
components/MainMap/MapFeatures.vue
components/MainMap/NavMenu.vue
components/Map/Map.vue
components/MenuNavbar.vue
components/PoisCard/PoiCard.vue
components/UI/Badge.vue
components/UI/FavoriteIcon.vue
components/UI/IconButton.vue
components/UI/Logo.vue
components/UI/UIButton.vue
cypress/e2e/home-content.cy.ts
locales/en-GB.ts
locales/es-ES.ts
locales/fr-FR.ts

- Fixes #566 
- Reduce border-radius on Logo
- Popup should push the map and not be an overlay.
- UX improvments on Search bar: #577
[Screencast from 2025-05-28 15-01-26.webm](https://github.com/user-attachments/assets/8ba71830-cb91-4afb-bebe-43c882e91957)

Move cta into bottom navbar

---

components/Map/Map.vue
components/Map/MapBase.vue
components/Map/MapPois.vue
components/PoisCard/PoiCardContent.vue
components/UI/UIButton.vue

[Screencast from 2025-06-30 15-06-12.webm](https://github.com/user-attachments/assets/5d59af17-ae22-40d2-82ff-b23a6c2e1b0a)

[details] - Add popup on poi click

---

components/BreadcrumbsWrapper.vue
components/MenuNavbar.vue
components/Search/SearchInput.vue
locales/en-GB.ts
locales/es-ES.ts
locales/fr-FR.ts
stores/search.ts

Also resolves:
- Add cursor pointer on breadcrumbs
- Add final style on search input

Add tooltip on search button

---

components/PanoramaxViewer.client.vue
components/PoisDetails/Mapillary.vue
components/PoisDetails/PoiDetails.vue
declarations.d.ts
nuxt.config.ts
package.json
yarn.lock

Implement panoramax web viewer
